config/routes.rb
Rails.application.routes.draw do

  #ユーザー用
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  #管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  #管理者
  namespace :admin do
    root to: "homes#top"
    get '/users' => 'users#index', as: 'users'
    get '/users/:id' => 'users#show', as: 'user_show'
    get '/users/:id/edit' => 'users#edit', as: 'user_edit'
    get '/users/:id/profile' => 'users#profile', as: 'user_profile'
    post '/users/:id' => 'users#update', as: 'update'
    resources :posts, only: [:new, :create, :index, :show, :edit, :destroy, :update] do
      resource :nices, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
  end

  #ユーザー
  scope module: :public do
    root to: "homes#top"
    get '/about' => 'homes#about', as: 'about'
    get '/users/:id' => 'users#show', as: 'user'
    get '/users/information/edit' => 'users#edit', as: 'edit_customer'
    get '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'
    get '/users/:id/nice' => 'users#nices', as: 'nice'
    get "search" => "searches#search"
    patch '/users/information' => 'users#update', as: 'customer'
    patch '/users/deleteprocess' => 'users#deleteprocess', as: 'deleteprocess'
    resources :notifications, only: :index
    resources :posts, only: [:new, :create, :index, :show, :edit, :destroy, :update] do
      resource :nices, only: [:index, :create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :users do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :image
  has_many :posts, dependent: :destroy
  has_many :nices, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence: true
  validates :first_name, presence: true
  # 数字のみ
  validates :telephone_number, numericality: {only_integer: true}
  validates :nickname, presence: true

  def niced_by?(user)
    nices.exists?(user_id: user.id)
  end

  def self.looks(search, word)
    # 完全一致
    if search == "perfect_match"
      User.where("nickname LIKE?", "#{word}")
    #部分一致
    elsif search == "partial_match"
      User.where("nickname LIKE?","%#{word}%")
    else
      User.all
    end
  end

  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  def index
    #ユーザー一覧表示
    @users = User.all
  end

  def show
    #ユーザー個別表示
    @user = User.find(params[:id])
  end

  def edit
    #ユーザー情報編集
    @user = User.find(params[:id])
  end

  def profile
    #ユーザーのプロフィール表示
    @user = User.find(params[:id])
    #ユーザーの投稿一覧
    @posts = @user.posts
  end

  def update
    #ユーザーの情報編集
    @user = User.find(params[:id])
    #更新処理
    if @user.update(user_params)
      redirect_to admin_user_show_path(@user.id)
    else
    #更新失敗した場合
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:last_name, :first_name, :email, :nickname, :introduction, :telephone_number, :id, :is_active)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="col pt-3">
    <h4>
      <strong><%= @user.last_name + @user.first_name %>さんの会員情報編集</strong>
    </h4>
  </div>

<%= form_with model: @user, method: :post, url: admin_update_path(@user.id) do |f| %>

  <div class="row">
    <div class="col-3">
      <p>会員ID</p>
    </div>
    <div class="col-3">
      <p><%= @user.id %></p>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <p>氏名</p>
    </div>
    <div class="col-3">
      <p><%= f.text_field :last_name %></p>
    </div>
    <div class="col-3">
      <p><%= f.text_field :first_name %></p>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <p>ニックネーム</p>
    </div>
    <div class="col-3">
      <p><%= f.text_field :nickname %></p>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <p>自己紹介</p>
    </div>
    <div class="col-3">
      <p><%= f.text_area :introduction %></p>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <p>電話番号</p>
    </div>
    <div class="col-3">
      <%= f.text_field :telephone_number %>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <p>メールアドレス</p>
    </div>
    <div class="col-3">
      <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <p>会員ステータス</p>
    </div>
    <div class="col-3">
      <span>
        <%= f.radio_button :is_active, :true %>
        <%= f.label :is_active_true, "有効" %>
      </span>
      <span>
        <%= f.radio_button :is_active, :false %>
        <%= f.label :is_active_false, "退会" %>
      </span>
    </div>
  </div>

  <div class="row">
    <div class="col-3"></div>
    <div class="col-3">
      <%= f.submit "変更を保存", class:"btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/admin/users/index.html.erb
<div class="container p-4">
  <div class="row">
    <div class="col-3">
      <h4>
        <strong>会員一覧</strong>
      </h4>
    </div>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th class="col-3">会員ID</th>
        <th class="col-3">氏名</th>
        <th class="col-3">メールアドレス</th>
        <th class="col-3">会員ステータス</th>
      </tr>
    </thead>
    <tbody>
<% @users.each do |user| %>
      <tr>
        <th class="row"><%= user.id %></th>
        <td><%= link_to user.last_name + user.first_name, admin_user_show_path(user.id) %></td>
        <td><%= user.email %></td>
        <td>
          <% if user.is_active == true %>
            <p class="text-success">有効</p>
          <% else %>
            <p class="text-muted">退会</p>
          <% end %>
        </td>
      </tr>
<% end %>
    </tbody>
  </table>
</div>

app/views/admin/users/profile.html.erb
<div class="container p-4">
  <div class="row p-3">
    <div class="col-3">
      <% if @user.image.attached? %>
      <!-- ユーザーに画像がある場合 -->
        <div><%= image_tag @user.image, size: "100x100" %></div>
      <% else %>
      <!-- ユーザーに画像がない場合 -->
        <div><%= image_tag "no_image.jpg", size: "100x100" %></div>
      <% end %>
    </div>
  </div>
  <div class="row p-2">
    <h4 class="col-3">
      <!-- ニックネーム -->
      <%= @user.nickname %>
    </h4>
  </div>
  <div class="row p-2">
    <div class="col-3">
      <!-- 自己紹介 -->
      <%= @user.introduction %>
    </div>
  </div>
  <div class="pb-2">
    <!-- フォロー・フォロワー -->
    <%= render 'public/relationships/relationship', user: @user %>
  </div>
    <% @posts.each do |post| %>
  <div class="container border">
    <div class="row pt-3">
      <div class="col">
        <% if post.user.image.attached? %>
          <!-- ユーザーに画像がある場合 -->
          <%= image_tag post.user.image, size: "100x100" %>
        <% else %>
          <!-- ユーザーに画像がない場合 -->
          <%= image_tag "no_image.jpg", size: "100x100" %>
        <% end %>
        <%= post.user.nickname %>
      </div>
    </div>
    <div class="row pt-3">
      <div class="col">
        <%= link_to admin_post_path(post.id), style: "color: black" do %>
          <!-- テキスト -->
          <%= post.body %>
        <% end %>
      </div>
    </div>
    <div class="row pt-3">
      <div class="col">
        <%= link_to admin_post_path(post.id), style: "color: black" do %>
          <% if post.image.attached? %>
          <!-- 画像を投稿する場合-->
            <%= image_tag post.image, size: "200x200" %>
          <% else %>
          <!-- 画像を投稿しない場合-->
            <td></td>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="row pt-3 pb-3">
      <div class="col">
        <!-- 投稿日 -->
        <%= post.created_at.strftime('%Y/%m/%d') %>
      </div>
    </div>
  </div>
    <% end %>
</div>

app/views/admin/users/show.html.erb
<div class="container p-4">
  <div class="row">
    <div class="col">
      <h4>
        <strong><%= @user.last_name + @user.first_name %>さんの会員詳細</strong>
      </h4>
    </div>
  </div>
  <table class="table table-bordered">
    <tbody>
      <tr>
        <td class="table-secondary col-1">会員ID</td>
        <td class="col-4"><%= @user.id %></td>
      </tr>
      <tr>
        <td class="table-secondary col-1">氏名</td>
        <td class="col-4"><%= @user.last_name %> <%= @user.first_name %></td>
      </tr>
      <tr>
        <td class="table-secondary col-1">ニックネーム</td>
        <td class="col-4"><%= @user.nickname %>
      </tr>
      <tr>
        <td class="table-secondary col-1">電話番号</td>
        <td class="col-4"><%= @user.telephone_number %></td>
      </tr>
      <tr>
        <td class="table-secondary col-1">メールアドレス</td>
        <td class="col-4"><%= @user.email %></td>
      </tr>
      <tr>
        <td class="table-secondary col-1">会員ステータス</td>
        <td class="col-4">
          <% if @user.is_active == true %>
            <p class="text-success">有効</p>
          <% else %>
            <p class="text-muted">退会</p>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
  <div class="row">
    <div class="col-3">
      <p><%= link_to '編集する', admin_user_edit_path, class:"btn btn-success" %></p>
    </div>
    <div class="col-3">
      <p><%= link_to 'プロフィール', admin_user_profile_path(@user.id), class:"btn btn-primary" %></p>
    </div>
  </div>
</div>