config/routes.rb
Rails.application.routes.draw do

  #ユーザー用
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  #管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  #管理者
  namespace :admin do
    root to: "homes#top"
    get '/users' => 'users#index', as: 'users'
    get '/users/:id' => 'users#show', as: 'user_show'
    get '/users/:id/edit' => 'users#edit', as: 'user_edit'
    get '/users/:id/profile' => 'users#profile', as: 'user_profile'
    post '/users/:id' => 'users#update', as: 'update'
    resources :posts, only: [:new, :create, :index, :show, :edit, :destroy, :update] do
      resource :nices, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
  end

  #ユーザー
  scope module: :public do
    root to: "homes#top"
    get '/about' => 'homes#about', as: 'about'
    get '/users/:id' => 'users#show', as: 'user'
    get '/users/information/edit' => 'users#edit', as: 'edit_customer'
    get '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'
    get '/users/:id/nice' => 'users#nices', as: 'nice'
    get "search" => "searches#search"
    patch '/users/information' => 'users#update', as: 'customer'
    patch '/users/deleteprocess' => 'users#deleteprocess', as: 'deleteprocess'
    resources :notifications, only: :index
    resources :posts, only: [:new, :create, :index, :show, :edit, :destroy, :update] do
      resource :nices, only: [:index, :create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :users do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_admin_header.html.erb
<% if admin_signed_in? %>
  <ul class="navbar-nav ml-auto">
    <li>
      <%= link_to admin_posts_path, class:"btn btn-outline-dark mr-3" do %>
        <i class="fa-solid fa-house"></i>投稿一覧
      <% end %>
    </li>
    <li>
      <%= link_to admin_users_path, class:"btn btn-outline-dark mr-3" do %>
        <i class="fa-solid fa-user"></i>会員一覧
      <% end %>
    </li>
    <li>
      <%= link_to destroy_admin_session_path, method: :delete, class:"btn btn-outline-dark" do %>
        <i class="fas fa-sign-out-alt"></i>ログアウト
      <% end %>
    </li>
  </ul>
<% end %>

app/views/layouts/_admin_post.html.erb
<div class="container">
  <div class="row p-4">
    <h4>
      <strong>投稿一覧</strong>
    </h4>
  </div>
  <!-- 投稿を順番に表示 -->
    <% posts.each do |post| %>
  <div class="container border">
    <div class="row pt-3">
      <div class="col">
        <%= link_to admin_user_show_path(post.user.id), style: "color: black" do %>
          <% if post.user.image.attached? %>
            <!-- ユーザーに画像がある場合 -->
            <%= image_tag post.user.image, size: "100x100" %>
          <% else %>
            <!-- ユーザーに画像がない場合 -->
            <%= image_tag "no_image.jpg", size: "100x100" %>
          <% end %>
            <%= post.user.nickname %>
        <% end %>
      </div>
    </div>
    <div class="row pt-3">
      <div class="col">
        <%= link_to admin_post_path(post.id), style: "color: black" do %>
        <!-- テキスト -->
          <%= post.body %>
        <% end %>
      </div>
    </div>
    <div class="row pt-3 pb-3">
      <div class="col">
        <%= link_to admin_post_path(post.id), style: "color: black" do %>
          <% if post.image.attached? %>
          <!-- 画像を投稿する場合-->
            <%= image_tag post.image, size: "200x200" %>
          <% else %>
          <!-- 画像を投稿しない場合-->
            <td></td>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="row pt-3 pb-3">
      <div class="col">
        <!-- 投稿日 -->
        <%= post.created_at.strftime('%Y/%m/%d') %>
      </div>
    </div>
  </div>
    <% end %>
</div>

app/views/layouts/_public_post.html.erb
    <% posts.each do |post| %>
  <div class="container border">
    <div class="row pt-3">
      <div class="col">
        <% if post.user.image.attached? %>
        <!-- ユーザーに画像がある場合 -->
          <%= image_tag post.user.image, size: "100x100" %>
        <% else %>
        <!-- ユーザーに画像がない場合 -->
          <%= image_tag "no_image.jpg", size: "100x100" %>
        <% end %>
        <%= link_to user_path(post.user.id), style: "color: black" do %>
          <%= post.user.nickname %>
        <% end %>
      </div>
    </div>
    <div class="row pt-3">
      <div class="col">
        <%= link_to post_path(post.id), style: "color: black" do %>
        <!-- テキスト -->
          <%= post.body %>
        <% end %>
      </div>
    </div>
    <div class="row pt-3">
      <div class="col">
        <%= link_to post_path(post.id), style: "color: black" do %>
        <!-- 画像を投稿する場合-->
          <% if post.image.attached? %>
            <%= image_tag post.image, size: "200x200" %>
          <% else %>
          <!-- 画像を投稿しない場合-->
            <td></td>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="row pt-3">
      <div class="col">
        <!-- コメントの件数-->
        <%= link_to "#{post.comments.count} コメント", post_path(post.id) %>
        <!-- いいねの件数-->
        <% if post.niced_by?(current_user) %>
          <p>
            <%= link_to post_nices_path(post), method: :delete do %>
              ♥<%= post.nices.count %> いいね
            <% end %>
          </p>
          <% else %>
          <p>
            <%= link_to post_nices_path(post), method: :post do %>
              ♡<%= post.nices.count %> いいね
            <% end %>
          </p>
        <% end %>
      </div>
    </div>
    <div class="row pt-3 pb-3">
      <div class="col">
        <!-- 投稿日 -->
        <%= post.created_at.strftime('%Y/%m/%d') %>
      </div>
    </div>
  </div>
    <% end %>

app/views/layouts/_search.html.erb
<% if user_signed_in? %>
  <div class="search_form mr-3">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <!-- ユーザーか投稿か選択 -->
      <%= f.select :range, options_for_select([['User'], ['Post']]) %>
      <!-- 完全一致か部分一致 -->
      <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["部分一致","partial_match"]]) %>
      <!-- 検索 -->
      <%= f.submit "検索", class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

app/views/layouts/_user_header.html.erb
<% if user_signed_in? %>
  <!-- ユーザーでログインしている場合-->
  <ul class="navbar-nav ml-auto">
    <li>
      <%= render 'layouts/search' %>
    </li>
    <li>
      <%= link_to notifications_path, class:"btn btn-outline-dark mr-3" do %>
        <i class="fa-solid fa-bell"></i>通知
      <% end %>
    </li>
    <li>
      <%= link_to user_path(current_user), class:"btn btn-outline-dark mr-3" do %>
        <i class="fa-solid fa-user"></i>プロフィール
      <% end %>
    </li>
    <li>
      <%= link_to posts_path, class:"btn btn-outline-dark mr-3" do %>
        <i class="fa-solid fa-house"></i>投稿一覧
      <% end %>
    </li>
    <li>
      <%= link_to destroy_user_session_path , method: :delete, class:"btn btn-outline-dark" do %>
        <i class="fas fa-sign-out-alt"></i>ログアウト
      <% end %>
    </li>
  </ul>
<% elsif !admin_signed_in? %>
  <!-- ユーザーでログインしていない場合-->
  <ul class="navbar-nav ml-auto">
    <li>
      <%= link_to about_path, class:"btn btn-outline-dark mr-3" do %>
        <i class="fas fa-link"></i>概要
      <% end %>
    </li>
    <li>
      <%= link_to posts_path, class:"btn btn-outline-dark mr-3" do %>
        <i class="fa-solid fa-house"></i>投稿一覧
      <% end %>
    </li>
    <li>
      <%= link_to new_user_registration_path, class:"btn btn-outline-dark mr-3" do %>
        <i class="fas fa-user-plus"></i>新規登録
      <% end %>
    </li>
    <li>
      <%= link_to new_user_session_path, class:"btn btn-outline-dark" do %>
        <i class="fas fa-sign-in-alt"></i>ログイン
      <% end %>
    </li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Riders</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/f2a363fe33.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light border-bottom border-dark p-4">
        <div class="container">
          <%= link_to root_path, class:"btn btn-outline-dark" do %>
            <h3>Riders</h3><h4 class="fa-solid fa-motorcycle"></h4>
          <% end %>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <%= render 'layouts/admin_header' %>
            <%= render 'layouts/user_header' %>
          </div>
        </div>
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>